services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - ./logs/:/code/logs/
      - static:/code/static
    depends_on:
        postgres:
          condition: service_healthy
    env_file:
        - ../.env

  postgres:
    image: postgres:13.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
    env_file:
      - ../.env

volumes:
  postgres_data:
  static:
