# Generated by Django 4.2.4 on 2023-08-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer", models.CharField(max_length=256, verbose_name="Customer username (slug)")),
                ("item", models.CharField(max_length=256, verbose_name="Item name")),
                ("total", models.IntegerField(verbose_name="Total amount")),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                ("date", models.DateTimeField(verbose_name="Created Date")),
            ],
        ),
    ]
