# Generated by Django 4.2.4 on 2023-08-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer", models.CharField(max_length=256, verbose_name="Customer username (slug)")),
                ("item", models.CharField(max_length=256, verbose_name="Item name")),
                ("total", models.IntegerField(verbose_name="Total amount")),
                ("quantity", models.IntegerField(verbose_name="Quantity items")),
                ("date", models.DateTimeField(verbose_name="Registered Date")),
            ],
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
