# Generated by Django 4.2.4 on 2023-08-06 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_deal_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "username",
                    models.SlugField(
                        max_length=256, primary_key=True, serialize=False, verbose_name="Customer username (slug)"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="deal",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.customer"),
        ),
    ]
