# Generated by Django 4.2.4 on 2023-08-07 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_deal_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("name", models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name="Item name")),
            ],
        ),
        migrations.AlterField(
            model_name="deal",
            name="item",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deals", to="api.item"),
        ),
    ]
